In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'D:\DATA ANALYST\data-analyst-journey\PYTHON\pandas series\file sample\world_population.csv')
df

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [3]:
df = pd.read_csv(r'D:\DATA ANALYST\data-analyst-journey\PYTHON\pandas series\file sample\world_population.csv', index_col='Country')
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [4]:
df.reset_index(inplace=True)

In [5]:
df

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [10]:
df.set_index('Country', inplace=True)
df

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [11]:
df.loc['Albania']

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [12]:
df.iloc[1]

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
Continent                         Europe
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: Albania, dtype: object

In [13]:
df.reset_index(inplace=True)
df

,Country,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,Afghanistan,36,AFG,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,Albania,138,ALB,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,Algeria,34,DZA,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,American Samoa,213,ASM,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,Andorra,203,AND,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,Wallis and Futuna,226,WLF,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,Western Sahara,172,ESH,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,Yemen,46,YEM,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,Zambia,63,ZMB,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,Zimbabwe,74,ZWE,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

In [14]:
df.set_index(['Continent','Country'], inplace=True)

In [15]:
df

                             Rank CCA3           Capital  2022 Population  \
Continent Country
Asia      Afghanistan          36  AFG             Kabul       41128771.0
Europe    Albania             138  ALB            Tirana        2842321.0
Africa    Algeria              34  DZA           Algiers       44903225.0
Oceania   American Samoa      213  ASM         Pago Pago          44273.0
Europe    Andorra             203  AND  Andorra la Vella          79824.0
...                           ...  ...               ...              ...
Oceania   Wallis and Futuna   226  WLF          Mata-Utu          11572.0
Africa    Western Sahara      172  ESH          El Aaiún         575986.0
Asia      Yemen                46  YEM             Sanaa       33696614.0
Africa    Zambia               63  ZMB            Lusaka       20017675.0
          Zimbabwe             74  ZWE            Harare       16320537.0

                             2020 Population  2015 Population  \
Continent Country
Asia      Afghanistan             38972230.0       33753499.0
Europe    Albania                  2866849.0        2882481.0
Africa    Algeria                 43451666.0       39543154.0
Oceania   American Samoa             46189.0          51368.0
Europe    Andorra                    77700.0          71746.0
...                                      ...              ...
Oceania   Wallis and Futuna          11655.0          12182.0
Africa    Western Sahara            556048.0         491824.0
Asia      Yemen                   32284046.0       28516545.0
Africa    Zambia                  18927715.0              NaN
          Zimbabwe                15669666.0       14154937.0

                             2010 Population  2000 Population  \
Continent Country
Asia      Afghanistan             28189672.0       19542982.0
Europe    Albania                  2913399.0        3182021.0
Africa    Algeria                 35856344.0       30774621.0
Oceania   American Samoa             54849.0          58230.0
Europe    Andorra                    71519.0          66097.0
...                                      ...              ...
Oceania   Wallis and Futuna          13142.0          14723.0
Africa    Western Sahara            413296.0         270375.0
Asia      Yemen                   24743946.0       18628700.0
Africa    Zambia                  13792086.0        9891136.0
          Zimbabwe                12839771.0       11834676.0

                             1990 Population  1980 Population  \
Continent Country
Asia      Afghanistan             10694796.0       12486631.0
Europe    Albania                  3295066.0        2941651.0
Africa    Algeria                 25518074.0       18739378.0
Oceania   American Samoa             47818.0          32886.0
Europe    Andorra                    53569.0          35611.0
...                                      ...              ...
Oceania   Wallis and Futuna          13454.0          11315.0
Africa    Western Sahara            178529.0         116775.0
Asia      Yemen                   13375121.0        9204938.0
Africa    Zambia                   7686401.0        5720438.0
          Zimbabwe                10113893.0        7049926.0

                             1970 Population  Area (km²)  Density (per km²)  \
Continent Country
Asia      Afghanistan             10752971.0    652230.0            63.0587
Europe    Albania                  2324731.0     28748.0            98.8702
Africa    Algeria                 13795915.0   2381741.0            18.8531
Oceania   American Samoa             27075.0       199.0           222.4774
Europe    Andorra                    19860.0       468.0           170.5641
...                                      ...         ...                ...
Oceania   Wallis and Futuna           9377.0       142.0            81.4930
Africa    Western Sahara             76371.0    266000.0             2.1654
Asia      Yemen                    6843607.0    527968.0            63.8232
Africa    Zambia                   4281671.0    752612.0            26.5976
          Zimbabwe                 5202918.0    390757.0            41.7665

                             Growth Rate  World Population Percentage
Continent Country
Asia      Afghanistan             1.0257                         0.52
Europe    Albania                 0.9957                         0.04
Africa    Algeria                 1.0164                         0.56
Oceania   American Samoa          0.9831                         0.00
Europe    Andorra                 1.0100                         0.00
...                                  ...                          ...
Oceania   Wallis and Futuna       0.9953                         0.00
Africa    Western Sahara          1.0184                         0.01
Asia      Yemen                   1.0217                         0.42
Africa    Zambia                  1.0280                         0.25
          Zimbabwe                1.0204                         0.20

[234 rows x 15 columns]

In [ ]:
df.sort_index()
df.sort_index(ascending=False)
df.sort_index(ascending=[False, True])

# pd.set_option('display.max.rows', 235)

                              Rank CCA3       Capital  2022 Population  \
Continent     Country
South America Argentina         33  ARG  Buenos Aires       45510318.0
              Bolivia           80  BOL         Sucre       12224110.0
              Brazil             7  BRA      Brasilia      215313498.0
              Chile             65  CHL      Santiago       19603733.0
              Colombia          28  COL        Bogota       51874024.0
...                            ...  ...           ...              ...
Africa        Tunisia           79  TUN         Tunis       12356117.0
              Uganda            31  UGA       Kampala       47249585.0
              Western Sahara   172  ESH      El Aaiún         575986.0
              Zambia            63  ZMB        Lusaka       20017675.0
              Zimbabwe          74  ZWE        Harare       16320537.0

                              2020 Population  2015 Population  \
Continent     Country
South America Argentina            45036032.0       43257065.0
              Bolivia              11936162.0       11090085.0
              Brazil              213196304.0      205188205.0
              Chile                19300315.0       17870124.0
              Colombia             50930662.0       47119728.0
...                                       ...              ...
Africa        Tunisia              12161723.0       11557779.0
              Uganda               44404611.0       37477356.0
              Western Sahara         556048.0         491824.0
              Zambia               18927715.0              NaN
              Zimbabwe             15669666.0       14154937.0

                              2010 Population  2000 Population  \
Continent     Country
South America Argentina            41100123.0       37070774.0
              Bolivia              10223270.0        8592656.0
              Brazil              196353492.0      175873720.0
              Chile                17004162.0       15351799.0
              Colombia                    NaN       39215135.0
...                                       ...              ...
Africa        Tunisia              10895063.0        9893316.0
              Uganda               32341728.0       24020697.0
              Western Sahara         413296.0         270375.0
              Zambia               13792086.0        9891136.0
              Zimbabwe             12839771.0       11834676.0

                              1990 Population  1980 Population  \
Continent     Country
South America Argentina            32637657.0       28024803.0
              Bolivia               7096194.0        5736088.0
              Brazil              150706446.0      122288383.0
              Chile                13342868.0       11469828.0
              Colombia             32601393.0       26176195.0
...                                       ...              ...
Africa        Tunisia               8440023.0        6578156.0
              Uganda               17586630.0       13284026.0
              Western Sahara         178529.0         116775.0
              Zambia                7686401.0        5720438.0
              Zimbabwe             10113893.0        7049926.0

                              1970 Population  Area (km²)  Density (per km²)  \
Continent     Country
South America Argentina            23842803.0   2780400.0            16.3683
              Bolivia               4585693.0   1098581.0            11.1272
              Brazil               96369875.0   8515767.0            25.2841
              Chile                 9820481.0    756102.0            25.9274
              Colombia             20905254.0   1141748.0            45.4339
...                                       ...         ...                ...
Africa        Tunisia               5047404.0    163610.0            75.5218
              Uganda               10317212.0    241550.0           195.6100
              Western Sahara          76371.0    266000.0             2.1654
              Zambia                4281671.0    752612.0            26.5976
              Zimbabwe              5202918.0    390757.0            41.7665

                              Growth Rate  World Population Percentage
Continent     Country
South America Argentina            1.0052                         0.57
              Bolivia              1.0120                         0.15
              Brazil               1.0046                         2.70
              Chile                1.0057                         0.25
              Colombia             1.0069                         0.65
...                                   ...                          ...
Africa        Tunisia              1.0076                         0.15
              Uganda               1.0304                         0.59
              Western Sahara       1.0184                         0.01
              Zambia               1.0280                         0.25
              Zimbabwe             1.0204                         0.20

[234 rows x 15 columns]

In [23]:
df.loc['Africa']
df.loc['Africa', 'Angola']

Rank                                   42
CCA3                                  AGO
Capital                            Luanda
2022 Population                35588987.0
2020 Population                33428485.0
2015 Population                28127721.0
2010 Population                23364185.0
2000 Population                16394062.0
1990 Population                11828638.0
1980 Population                 8330047.0
1970 Population                 6029700.0
Area (km²)                      1246700.0
Density (per km²)                 28.5466
Growth Rate                        1.0315
World Population Percentage          0.45
Name: (Africa, Angola), dtype: object

In [ ]:
df.iloc[1] # iloc doesn't work with multi-indexing

Rank                                 138
CCA3                                 ALB
Capital                           Tirana
2022 Population                2842321.0
2020 Population                2866849.0
2015 Population                2882481.0
2010 Population                2913399.0
2000 Population                3182021.0
1990 Population                3295066.0
1980 Population                2941651.0
1970 Population                2324731.0
Area (km²)                       28748.0
Density (per km²)                98.8702
Growth Rate                       0.9957
World Population Percentage         0.04
Name: (Europe, Albania), dtype: object